### ISSUE TITLE
Fuzzing doesn't work

### ISSUE THREAD

**Issue by pyfisch** [pyfisch/cbor#102]
``` 
$ cargo fuzz run from_slice
error: failed to select a version for `serde_cbor`.
    ... required by package `serde_cbor-fuzz v0.0.1 (/cbor/fuzz)`
versions that meet the requirements `= 0.9.0` are: 0.9.0

the package `serde_cbor-fuzz` depends on `serde_cbor`, with features: `serde_bytes` but `serde_cbor` does not have these features.


failed to select a version for `serde_cbor` which could resolve this conflict
error: could not build fuzz script: "cargo" "build" "--manifest-path" "/cbor/fuzz/Cargo.toml" "--verbose" "--bin" "from_slice" "--target" "x86_64-unknown-linux-gnu"⏎                                                                                            
```

Somehow it requires the `serde_bytes` crate as a dependency and not as a dev-dependency but I have no idea why it is needed at all for fuzzing.

**Comment by sfackler** [comment]
It looks like this isn't a fuzz-specific problem, but actually a problem with anything that depends on the crate. The default-enabled std feature enables `serde-bytes/std`, but it seems like that breaks when not building serde_cbor itself since dev dependencies aren't included?

**Comment by baloo** [comment]
I can confirm what @sfackler is saying, to me master is broken, and `no-std` feature does not work either:
```error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/de.rs:700:18
    |
700 | impl<'de, 'a, R> de::Deserializer<'de> for &'a mut Deserializer<R>
    |                  ^^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/de.rs:820:18
    |
820 | impl<'de, 'a, R> de::SeqAccess<'de> for SeqAccess<'a, R>
    |                  ^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/de.rs:857:18
    |
857 | impl<'de, 'a, R> de::SeqAccess<'de> for IndefiniteSeqAccess<'a, R>
    |                  ^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/de.rs:892:18
    |
892 | impl<'de, 'a, R> de::MapAccess<'de> for MapAccess<'a, R>
    |                  ^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/de.rs:936:18
    |
936 | impl<'de, 'a, R> de::MapAccess<'de> for IndefiniteMapAccess<'a, R>
    |                  ^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/de.rs:968:18
    |
968 | impl<'de, 'a, R> de::EnumAccess<'de> for UnitVariantAccess<'a, R>
    |                  ^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/de.rs:984:18
    |
984 | impl<'de, 'a, R> de::VariantAccess<'de> for UnitVariantAccess<'a, R>
    |                  ^^^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
    --> /home/baloo/work/dev/cbor/src/de.rs:1029:14
     |
1029 | impl<'de, T> de::EnumAccess<'de> for VariantAccess<T>
     |              ^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
    --> /home/baloo/work/dev/cbor/src/de.rs:1049:14
     |
1049 | impl<'de, T> de::VariantAccess<'de> for VariantAccess<T>
     |              ^^^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
    --> /home/baloo/work/dev/cbor/src/de.rs:1163:14
     |
1163 | impl<'de, T> de::EnumAccess<'de> for VariantAccessMap<T>
     |              ^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
    --> /home/baloo/work/dev/cbor/src/de.rs:1183:14
     |
1183 | impl<'de, T> de::VariantAccess<'de> for VariantAccessMap<T>
     |              ^^^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/error.rs:220:6
    |
220 | impl de::Error for Error {
    |      ^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/error.rs:234:6
    |
234 | impl ser::Error for Error {
    |      ^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/ser.rs:346:13
    |
346 | impl<'a, W> ser::Serializer for &'a mut Serializer<W>
    |             ^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/ser.rs:680:13
    |
680 | impl<'a, W> ser::SerializeTuple for &'a mut Serializer<W>
    |             ^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/ser.rs:701:13
    |
701 | impl<'a, W> ser::SerializeTupleStruct for &'a mut Serializer<W>
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/ser.rs:722:13
    |
722 | impl<'a, W> ser::SerializeTupleVariant for &'a mut Serializer<W>
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/ser.rs:830:13
    |
830 | impl<'a, W> ser::SerializeStruct for StructSerializer<'a, W>
    |             ^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/ser.rs:856:13
    |
856 | impl<'a, W> ser::SerializeStructVariant for StructSerializer<'a, W>
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/ser.rs:902:13
    |
902 | impl<'a, W> ser::SerializeSeq for CollectionSerializer<'a, W>
    |             ^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`

error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
   --> /home/baloo/work/dev/cbor/src/ser.rs:923:13
    |
923 | impl<'a, W> ser::SerializeMap for CollectionSerializer<'a, W>
    |             ^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`



```

**Comment by pyfisch** [comment]
If no one figure this out probably the best way forward is to remove `serde_bytes` as a dependency entirely.
