### ISSUE TITLE
serialize_f64 is too clever

### ISSUE THREAD

**Issue by Nadrieril** [pyfisch/cbor#109]
The [`serialize_f64`](https://github.com/pyfisch/cbor/blob/9df0c6f0ab8af0d0782c085318caea33df626bc7/src/ser.rs#L471-L479) method of the cbor serializer tries to be clever: if the provided value fits in a `f32` or `f16`, it uses the shorter representation to save bytes.
I'm using cbor in a context where the output is passed through a hash function, so the precise representation chosen is important. The problem I have is that I have no way of telling the cbor serializer to use only the `f64` size.
Would it be possible to make the `serialize_f64` method always use the `f64` representation ? I also think that's what would be expected by serde consumers in general.

**Comment by pyfisch** [comment]
[Section 3.6](https://tools.ietf.org/html/rfc7049#section-3.6) states that an encoder can encode a number in any way it likes to as long as the numeric value stays identical but applications may specify something else.

It should be noted that serde can't decode integer values if they are stored as floats (If I recall correctly).

> I'm using cbor in a context where the output is passed through a hash function, so the precise representation chosen is important.

As long as the encoder always uses the same encoding scheme I don't see a problem with using `f32` and `f16` in place of `f64`.

> Would it be possible to make the serialize_f64 method always use the f64 representation ? I also think that's what would be expected by serde consumers in general.

Can you give an example of an encoder expecting this?

**Comment by Nadrieril** [comment]
> As long as the encoder always uses the same encoding scheme I don't see a problem with using `f32` and `f16` in place of `f64`.

That's only if there is only one encoder used. I'm working on the Rust implementation of the [Dhall language](https://github.com/dhall-lang/dhall-lang), and this language in particular allows adding integrity checks to files. Those integrity checks work by encoding the file as binary (following a precise encoding specification), and then hashing the result. But because the language has several implementations (in different languages), it is important that all of them use the exact same binary encoding.
The dhall standard specifies how to encode doubles [here](https://github.com/dhall-lang/dhall-lang/blob/master/standard/binary.md#double). I don't see a way to use `serde_cbor` to produce that encoding. I tried using `serialize_bytes` but that can't work to produce floats.

**Comment by Nadrieril** [comment]
Here's my reasoning behind changing the behavior. There are two possible behaviors one may want when encoding a f64 value:
1. encode the f64 as the smallest representation possible;
2. encode the f64 as f64.

With the current behavior, 1. is automatic and 2. is impossible. If we made instead 2. the default, then 2. would be automatic and 1. would be doable with a small workaround like a `deserialize_with` annotation or a wrapper struct.
Since I expect very few people will actually care about which is used, I feel like 2. would be a good choice.

**Comment by pyfisch** [comment]
The Dhall language is an interesting use-case for CBOR. The referenced specification says that `Double` shall be stored as `Single` if possible and the special float values are stored as `Half`.

Since you are the first person asking for this feature I'd suggest you fork the crate for now and make the necessary changes. For example [bignums](https://github.com/dhall-lang/dhall-lang/blob/master/standard/binary.md#variables-1) are not currently supported by serde_cbor.

**Comment by singpolyma-shopify** [comment]
@Nadrieril I just saw this -- this might be a good reason to re-visit why Dhall is not using canonical CBOR for floats (which I believe this crate is using and I also had to patch special support for into my ruby CBOR library).
