### ISSUE TITLE
Add byte_offset() method for StreamDeserializer.

### ISSUE THREAD

**Issue by ChaseElectr** [pyfisch/cbor#110]
I'm using serde_cbor as serializer and store datas in a file side by side. When I read the file and deserializing datas, I want to remember every data's offset in the file so that I don't need to keep the entire file in the memory. But only the struct Deserializer has a byte_offset() method, and StreamDeserializer not. I think we can easily add it.

**Comment by pyfisch** [comment]
I believe this is done?
