### ISSUE TITLE
What if I don't want the packed serialization?

### ISSUE THREAD

**Issue by thanatos** [pyfisch/cbor#112]
I'm trying to avoid having a format that inadvertently works. While avoiding serialization is a matter of just not calling the `_packed` functions, deserialization seems to implicitly always use it.

E.g., coding against a spec, I do not want other, incorrect (according to the spec, which might be agnostic to Rust/`serde_cbor`) to successfully deserialize, lest someone thinks that format *is* supported.

**Comment by pyfisch** [comment]
> I'm trying to avoid having a format that inadvertently works. While avoiding serialization is a matter of just not calling the _packed functions, deserialization seems to implicitly always use it.

Your assessment is unfortunately correct. In the next version I want to change the default serialization of enums anyway (#85) so I might as well make de-serialization more restrictive.

**Comment by pyfisch** [comment]
@dtolnay Serde deserializes maps with numbered keys like `{0: "foo", 1: 42}` to structures like `struct Foo {name: String, age: u32}`, is there a way to opt-out of this and only accept named keys?

**Comment by baloo** [comment]
From my understanding, this is only code generated in the serde_derive deserializer. You may remove that behavior by manually implementing the Deserializer.

I also have another use-case where *by spec* the format is packed, with custom indexes:
https://github.com/mozilla/authenticator-rs/blob/df28de2/src/ctap2/commands.rs#L1178
https://github.com/mozilla/authenticator-rs/blob/df28de2/cose/src/lib.rs#L174

I'd be interested to get support for that in serde_derive, that would save a ton of repetitive code.

**Comment by dtolnay** [comment]
> is there a way to opt-out of this and only accept named keys?

One way would be that if the Deserializer is called with deserialize_struct then use an implementation of MapAccess whose next_key only allows string keys. In serde_json we do the same thing. The relevant code is https://github.com/serde-rs/json/blob/v1.0.39/src/de.rs#L1763-L1768

**Comment by baloo** [comment]
I implemented that in #126, thank you @dtolnay !

**Comment by baloo** [comment]
this issue is fixed in master and should be closed
