### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by baloo** [pyfisch/cbor#119]
The last release available for this crate is 0.9 which is 10 month old. There is a couple of improvement pending in master that I would need, and a newer release would be nice.

@pyfisch It looks like you've been submitted a couple of changes lately. Would you be able to list all tasks/fixes required before a release? I can try to help with some of them.

Thanks!

**Comment by pyfisch** [comment]
Hi @baloo, I would appreciate your help.

These are the things that should be done before a release:

* [ ] complete the [deserializer-options](https://github.com/pyfisch/cbor/tree/deserializer-options) branch
  * [ ] test that if `accept_standard_enums` is false no enums-as-map can be deserialized
  * [ ] test that if `accept_legacy_enums` is false no enums formatted as arrays can be deserialized
  * [ ] if both are false no enums at all can be deserialized
  * [ ] (optional) find a way to disable the packed format in the deserializer (See #112), but I only want to support this if it does not require much extra code
    * [ ] write tests for this
* [ ] write a How-To for no-std usage (should be included on main page of API docs)
* [ ] add an example to the `StreamDeserializer`
* [ ] update main page of API docs (I can do this myself, but if you want to do this, reach out to me and ask me what should be in the text)

**Comment by baloo** [comment]
I have a hard time understanding how the packed format is actually deserialized. I'm not sure I can pull that one off :(

**Comment by pyfisch** [comment]
> I have a hard time understanding how the packed format is actually deserialized. I'm not sure I can pull that one off :(

Yeah, I initially assumed it was implemented in this crate but mapping the numbers to named fields and variants appears to be built-in serde magic.

**Comment by baloo** [comment]
@pyfisch let me know if you want me to do the last item on the list, and as mentioned, if so let me know about any content you'd want on that page.

**Comment by pyfisch** [comment]
@baloo for the docs just have a look that they are up-to-date (e.g. don't reference any removed functions. The long example document with John Doe should be removed as I don't think anymore it is that helpful. Instead there should be a usage example like in the readme (or the same example copied).

**Comment by baloo** [comment]
Anything missing for a release?

**Comment by baloo** [comment]
@pyfisch up?

**Comment by pyfisch** [comment]
## Making a Release

* [ ] Make sure the crate compiles and all tests pass.
* [ ] (Optional) Test that the fuzzer works and fuzz the crate for some time.
* [ ] Write a list with all changes made since the last release
* [ ] Increment the version number in `Cargo.toml` and the `README.md`. Bugfixes increase the patch version while new features or an increased minimum Rust version require a new minor version.
* [ ] Check that the file `examples/readme.rs` and the example from the `README.md` match.
* [ ] Commit the changes.
* [ ] Add a git tag with the new version number:
    `git tag "v42.0.2"`
* [ ] Push the changes: `git push --tags`
* [ ] Run `cargo publish`
* [ ] Add a new release to GitHub with a list of changes.

**Comment by pyfisch** [comment]
* `no_std` support!
* The default enum format was changed. It now uses the [externally tagged](https://serde.rs/enum-representations.html) format recommended by serde.
    One can optionally serialize to the legacy array-based format.
    Both formats are accepted for deserialization.
* Deserialization is configurable.
    Opt-out of the packed format or only accept one enum serialization.
* `Value` variants were renamed and simplified.
* Keys of `Value` maps are now sorted in a canonical order.
* Some utility methods for serialization and deserialization were removed
    because they saw little use.
* 128-bit numbers can be used, but bear in mind that the values are
    still limited to 64-bit by the CBOR format.
* Better docs and README.
* Bug fixes.

I would like to thank @sfackler, @chrysn, @ogoodman, @kcking, @wildarch and @baloo for their contributions to this release!

If you have any questions or problems with the new release please open an issue.

**Comment by baloo** [comment]
Thank you so much!
