### ISSUE TITLE
Change `Serialize::Error` to `io::Error`

### ISSUE THREAD

**Issue by Stebalien** [pyfisch/cbor#13]
Unless I'm mistaken, the serializer can't possibly spit out any error but an IO error. To make error handling simpler, it would be nice if `Serialize::Error` was set to `io::Error` instead of `serde_cbor::Error`. One can always just convert it to a `serde_cbor::Error` if necessary.

**Comment by pyfisch** [comment]
`Serialize::Error` must implement [`serde::ser::Error`](https://serde-rs.github.io/serde/serde/ser/trait.Error.html). While my serialization code can will only fail if the IO fails serialization may fail [for other reasons](https://github.com/serde-rs/serde/blob/89f0ad99a627494d49abf36b9de3876d8a4e2714/serde/src/ser/impls.rs#L697) like invalid values. These failures can't be represented in an IO error and for this reason I keep using the `serde_cbor::Error`. One could argue that `serde_cbor` should have separate errors for serialization and deserialization, but also serde_json uses a single error type.

**Comment by Stebalien** [comment]
I see. (Although, serde really should be serializing paths as bytes...)
