### ISSUE TITLE
Struct with named fields can be deserialized from sequence

### ISSUE THREAD

**Issue by portstrom** [pyfisch/cbor#138]
This [issue in Serde](https://github.com/serde-rs/serde/issues/1587) affects Serde Cbor.

Example code adapted to Serde Cbor:
```rust
use serde_derive::Deserialize;

#[derive(Debug, Deserialize)]
struct Person {
    first_name: String,
    last_name: String,
}

fn main() {
    let data = serde_cbor::to_vec(&("John", "Doe")).unwrap();
    eprintln!("{:?}", data);
    eprintln!("{:#?}", serde_cbor::from_slice::<Person>(&data));
}
```

**Comment by pyfisch** [comment]
Ok, this comes as a surprise to me.

**Comment by pyfisch** [comment]
I am not sure if this is an issue or rather just how serde works. If it causes problems it should be solved on the serde side.

**Comment by portstrom** [comment]
Even if this is an issue with serde, serde-cbor should have the issue open until it has been fixed upstream.

**Comment by pyfisch** [comment]
Fine. I don't think this is an issue but rather a feature of serde to help with the deserialization of some data formats that do not distinguish between arrays and maps. And I don't keep issues around for features people find surprising.

(Btw besides the example with structs and sequences it can be rather surpising how serialized data is deserialized in serde. Serde appears to follow Postel's law "be conservative in what you do, be liberal in what you accept from others" to enable working with various different formats. This can it make it difficult to code against a specification which exactly describes what is allowed and what must not be accepted.)
