### ISSUE TITLE
[Query] Can you please explain comparing serialization of "foobar" with bytes of "ffoobar"? Why the extra "f"?

### ISSUE THREAD

**Issue by PraneshAnubhav** [pyfisch/cbor#142]
https://github.com/pyfisch/cbor/blob/bb2993feb556d5b670663f240b2ac81ebe5e2415/tests/ser.rs#L6

**Comment by pyfisch** [comment]
The first byte from the serialization of "foobar" is 0x66 which happens to be the ASCII value of "f". This byte indicates that a string of length 6 follows.

See also. http://cbor.me/?diag=%22foobar%22
