### ISSUE TITLE
byte_offset not available for file reader

### ISSUE THREAD

**Issue by Don42** [pyfisch/cbor#158]
Thank you for your work on serde_cbor, it is quite useful.

# Description
I currently have a log-structured file containing independently written cbor encoded objects.
I'm trying to iterate through the file, reading and decoding all the objects, and noting the offset of each object in the file. This is supposed to allow later lookup without keeping the whole object in memory. Unfortunately I can get the `byte_offset` function to work. Apparently the Offset trait isn't implemented for a reader using a file.
Is there an easier way to read all file contents and get the offsets of each object? Am I doing something wrong with with the the deserializer?

# Compiler Error Message
```
error[E0599]: no method named `byte_offset` found for type `serde_cbor::de::Deserializer<serde_cbor::read::IoRead<std::fs::File>>` in the current scope
   --> src/lib.rs:152:26
    |
152 |             offset = des.byte_offset() as u64;
    |                          ^^^^^^^^^^^
    |
    = note: the method `byte_offset` exists but the following trait bounds were not satisfied:
            `serde_cbor::read::IoRead<std::fs::File> : serde_cbor::read::Offset`

```

# Example code
```rust
let mut des = serde_cbor::Deserializer::from_reader(file);
let offset = des.byte_offset() as u64;
```

# Context
I'm working through a [rust course](https://github.com/pingcap/talent-plan/blob/master/rust/projects/project-2/project.md). One of the steps is keeping the offsets for each key-value-pair in the file in memory to access the value later.

**Comment by pyfisch** [comment]
Hi Don42,

are you aware of the [`StreamDeserializer`](https://docs.rs/serde_cbor/0.10.2/serde_cbor/struct.StreamDeserializer.html). It might be useful to decode the log file.

@baloo Do you recall, why in #101 `Offset` is implemented for `SliceRead` but not for `IoRead`? `IoRead` contains an `offset` field within the `OffsetReader`.
If I don't miss something it is straightforward to add `byte_offset`.

**Comment by baloo** [comment]
most likely because I forgot to :/

**Comment by Don42** [comment]
@pyfisch I knew it existed, but I didn't think of calling `next()` directly. Thanks for the idea. Now I can confirm I get the same issue with the `StreamDeserializer`.

**Comment by pyfisch** [comment]
@Don42 I have created a new branch with byte_offset for file reader. You could add a git dependency to your Cargo.toml and try it out.

**Comment by Don42** [comment]
@pyfisch Seems to work for my usecase. :+1:
