### ISSUE TITLE
to_value and from_value functions

### ISSUE THREAD

**Issue by MikeeyBikeey** [pyfisch/cbor#170]
I need something like serde_json's [`to_value`](https://docs.serde.rs/serde_json/fn.to_value.html) and [`from_value`](https://docs.serde.rs/serde_json/fn.from_value.html).
Are there plans for adding `to_value` and `from_value` for serde_cbor?
Is it possible to add to serde_cbor? (My knowledge about serializers is limit)

Thanks!

**Comment by pyfisch** [comment]
https://docs.rs/serde_cbor/0.10.2/serde_cbor/value/index.html

This crate contains a `to_value` and a `from_value` function. Are the functions provided by serde-json different in some way?

**Comment by MikeeyBikeey** [comment]
Oh, sorry serde_json has it in its crate-root so when I didn't see it in serde_cbor's crate-root I assumed it didn't exist.

Thanks for the clarification.

**Comment by pyfisch** [comment]
You're welcome!
