### ISSUE TITLE
CI jobs seem to fail because of rustfmt problems is already-existing code

### ISSUE THREAD

**Issue by stevenroose** [pyfisch/cbor#196]
I generally prefer not to enforce formatting on a project, but I accept if projects prefer to do that.

But shouldn't it be made sure that all existing code follows the formatting rules before starting the enforcement?

**Comment by pyfisch** [comment]
> But shouldn't it be made sure that all existing code follows the formatting rules before starting the enforcement?

Existing code did follow the formatting rules but rustfmt changed, as you can see in the commit history. No big deal.

I am not sure if you are aware but this crate is looking for a rewrite and a new maintainer (#179). @hansl is working on it but in the meantime I'd rather not spend too much time improving the existing codebase and only fix bugs which severly impact users.

**Comment by stevenroose** [comment]
Hmm, ok makes sense. Feel free to decide whether to merge #192 or just close both the PR and this issue without merging.
