### ISSUE TITLE
Question: 0xff as padding

### ISSUE THREAD

**Issue by jamessewell** [pyfisch/cbor#210]
(this is a question not an issue, hope that's OK)

I have a `[u8]` which I am incrementally filling with CBOR fragments. I need a value that I can init the array with, at the moment I'm using `0xff` - but I'm not sure this is strictly correct.

I'm after the following semantics:

1. Stream decoding will fail when I hit the first non-filled area of the array
1. When decoding fails I can identify the restart position as the start of the last failed element 

I'm using a function which decodes as far as it can then returns the offset it got up to as per below:

```rust
fn consume_cbor(offset: usize, data: &[u8]) -> usize {
    {
        let mut last_element_failed = false;
        let mut d =
            serde_cbor::de::Deserializer::from_slice(&data[offset..]).into_iter::<MyStruct>();

        let taken = d
            .by_ref()
            .take_while(|t| {
                if t.is_err() {
                    last_element_failed = true
                };
                t.is_ok()
            })
            .map(|m| m.unwrap())
            .collect::<Vec<MyStruct>>();

        match last_element_failed {
            false => d.byte_offset(),
            true => d.byte_offset() - 1,
        }
    }
}
```

Does this seem sane? I'm concerned that `0xff` isn't strictly EOF (which is what I want). Should I be using something else? An unused character?

I'm also worried about my use of ` d.byte_offset() -1` when I get a stream failure. This works, but I can't tell if that's a side-effect or guaranteed.

Thanks, 
James

**Comment by pyfisch** [comment]
Hi James,

this use-case seems to be a bit odd to me. What are you trying to accomplish with your program?
From the question I understand that you repeatedly write data to a slice.
Do you send or store the incomplete arrays somewhere?
You might want to look into streaming CBOR as described in the RFC.
Instead of a slice you can use a `Vec` to store the data. If that is not possible I'd suggest to at least store the length of the array somewhere else, so you don't have to loop through the slice to find the end.

**Comment by jamessewell** [comment]
It’s like a mpsc ring buffer implementation between processes. The data is
in shared memory so a vec can’t really be used.

The producers write cbor fragments incrementing an atomic write pointer,
while the consumer repeatedly uses the iterator (which is streaming cbor as
far as I can tell?) to deserialise as far as it can. So I’m only processing
until a gap then stopping - no looping though the whole array.

But it all hinges on me being able to identify dead areas in the array. Can
I use 0xff like this? Is there a better marker which will cause a
deserialise failure in all cases?

**Comment by pyfisch** [comment]
You can use 0xff like this. I'd probably still use two atomic pointers for begin+end of the live area of the array instead of relying on the contents of the buffer.

**Comment by jamessewell** [comment]
I am - but writing to the array isn’t atomic so I want to catch the edge
case of write pointer increments but not all cbor written.

Thanks!

**Comment by pyfisch** [comment]
> I am - but writing to the array isn’t atomic so I want to catch the edge
> case of write pointer increments but not all cbor written.

I am by no means an expert on atomic operations, but I recall from the lecture that you need synchronization if multiple processes read and write the same data. (The reading thread may see incomplete data (even with holes) or only see some updates to the data.)
On the other hand Rust guarantees that you can't share memory across processes without synchronization (`Send`, `Sync` traits) unless you use unsafe.

Please ask about this on Stackoverflow or the Rust user forum if somebody relies on this code.

**Comment by jamessewell** [comment]
Yeah I’ve been leaning on the IRC and discord people a lot - thanks for the
help!
