### ISSUE TITLE
Update to serde 0.9.0

### ISSUE THREAD

**Issue by dtolnay** [pyfisch/cbor#23]
Check out the release notes here: https://github.com/serde-rs/serde/releases/tag/v0.9.0

**Comment by dtolnay** [comment]
Whoa you are way ahead of me. Sorry! :sweat_smile:

**Comment by pyfisch** [comment]
All the credit goes to @sfackler. He is a terrific crate maintainer and updated serde-cbor before I could even respond to issue #22 he opened.
