### ISSUE TITLE
Packed format is broken/fragile

### ISSUE THREAD

**Issue by bennofs** [pyfisch/cbor#26]
The packed format for structs uses the order of the calls to `serialize_field` to decide on the id of the field for the map.

This is very fragile, and seems to break with the current serde-codegen generated code (sorry I don't have an example here, it's hard to extract the from my current project). I've had cases where a simple `to_writer_packed` / `from_reader` failed.

A more robust approach would be to serialize the fields as a sequence instead, as this makes it obvious that the order matters. Or look up the field name when serializing to determine the index in the struct fields array.

**Comment by pyfisch** [comment]
Using numbers as keys is recommended by the cbor spec instead of serializing as a sequence. I will add a note that the order of fields matters for packed encoding.

> Or look up the field name when serializing to determine the index in the struct fields array.

How do you mean this?

**Comment by bennofs** [comment]
Perhaps my reason I thought this issue occurred was wrong. Here's an example that reproduces the error: https://gist.github.com/81218cb280fc42f4eda958be1f241cf8

If you run that, you get a `Err(Syntax)`.

**Comment by bennofs** [comment]
The serialization appears to be correct:

```
$ cbor2json.rb serialized 
{
  "0": {
    "0": 170
  },
  "1": 204
}
```

**Comment by bennofs** [comment]
The serialized sequence looks like this: ` a2 00 a1 00 18 aa 01 18 cc`

**Comment by bennofs** [comment]
Ok, so the actual problem here is that `struct_fields` gets clobbered when we parse the inner struct and is not reset when we continue parsing the outer one. So it tries to lookup the index 1 in the list `["x"]` (fields of the inner struct) and fails.

**Comment by pyfisch** [comment]
Thank you for investigating the problem. I will think about how to best fix the issue.

**Comment by pyfisch** [comment]
Nested or inner structs are now parsed correctly. Is the issue solved for you too?

**Comment by bennofs** [comment]
I switched to using `serde-json` in the original project, so I cannot test this, but the test case looks fine.
