### ISSUE TITLE
Track path to deserialization errors

### ISSUE THREAD

**Issue by myfreeweb** [pyfisch/cbor#34]
https://github.com/serde-rs/serde/issues/919

Currently the serde_cbor errors are not very helpful, e.g.

    Custom("missing field `name`")

— no idea in what object.

**Comment by pyfisch** [comment]
Thanks for bringing this to my attention. Unfortunately I wont have time to add this soon but pull requests are welcome.

**Comment by pyfisch** [comment]
I've decided that the current errors are *good enough*.
