### ISSUE TITLE
What's the purpose of MAX_SEQ_LEN ?

### ISSUE THREAD

**Issue by tailhook** [pyfisch/cbor#39]
I need to serialize bytes longer than 0.5Mb. Can the constant be customized or just dropped?

**Comment by pyfisch** [comment]
The purpose of MAX_SEQ_LEN is to prevent corrupted files from allocating huge amounts of memory. CBOR declares sequence lengths and if a string or bytestring is really long CBOR currently will allocate memory for the expected string. A single string can allocate up to 2^64 bytes (or as much as the computer has memory) and crash the program. The file does not actually need to contain the string. MAX_SEQ_LEN limits this but it is both ineffective and and too restrictive. A better approach would be to allocate first a small buffer for a large string and then increase the size if the string is really found.

Do you want to send in a PR for this? I dont think customizing the constant is useful and dropping it the better approach.

**Comment by tailhook** [comment]
Well, I'm not sure growing buffer is needed. Big allocations > 128KiB are not allocated up front anyway because only virtual pages are allocated (the value is from jemalloc on linux, but I believe all systems have such mechanism). So the purpose of a limit is to avoid allocations approaching the size of the virtual memory. For `from_slice` the limit is obviously the size of a slice. For the streaming interface, I think it's still easy to choose the limit for your application.

On the other hand, growing buffer would make the code more complex, I'm not sure if that complexity is justified.

**Comment by pyfisch** [comment]
I did not think about slices limiting the input size. Since sequences
besides strings are not preallocated the limit can be removed there. For
streaming applications I will allow customizing the limit.
I will change the code this week.

Am 18.07.2017 11:11 vorm. schrieb "Paul Colomiets" <notifications@github.com

**Comment by tailhook** [comment]
@pyfisch sound like you haven't seen #39?

**Comment by tailhook** [comment]
Okay, #41 looks much simpler, and gets rid of the limit entirely.
