### ISSUE TITLE
`Option<T>` does not round-trip

### ISSUE THREAD

**Issue by apoelstra** [pyfisch/cbor#5]
```
extern crate serde_cbor;

fn main() {
    let obj1 = Some(10u32);

    let mut v = vec![];
    assert!(serde_cbor::ser::to_writer(&mut v, &obj1).is_ok());
    println!("{:?}", v);
    let obj2: Result<Option<u32>, _> = serde_cbor::de::from_reader(&v[..]);

    assert_eq!(obj1, obj2.unwrap());
}
```
This code fails with
```thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: SyntaxError(invalid syntax: "incorrect type", 0)', ../src/libcore/result.rs:738```

I have code in production that fails with "trailing bytes" when I have a structure whose last element is an Option; I haven't produced a small test case because it's such a PITA to write Serialize/Deserialize impls for structures.

**Comment by pyfisch** [comment]
This is a serde problem. The [deserialization to `Option`](https://github.com/serde-rs/serde/blob/v0.6.x/serde/src/de/impls.rs#L277) is not implemented for integer values. There is already an issue for this serde-rs/serde#217

**Comment by pyfisch** [comment]
The mentioned is was a bit different. So this is not fixed.

@erickt Is it possible to make options round trip in languages like JSON and CBOR?

**Comment by erickt** [comment]
@pyfisch: Yes, you should be able to. Here's how [serde_json does it](https://github.com/serde-rs/json/blob/master/json/src/de.rs#L537) by overriding `Deserializer::deserialize_option`.

**Comment by pyfisch** [comment]
Sorry that it took so long. It was a bit more complicated than expected since I had to add one byte lookahead to the parser to correctly parse options.
