### ISSUE TITLE
`[u8; 4]` seralized as array of 4 numbers instead of byte string.

### ISSUE THREAD

**Issue by vi** [pyfisch/cbor#53]
How do I use byte strings with serde_cbor?

I want `"64.71.168.211".parse::<std::net::Ipv4Addr>().unwrap().octets()` to be `54 40 47 a8 d3`, not   `84 18 40 18 47 18 a8 18 d3`.

**Comment by sfackler** [comment]
You can use https://docs.rs/serde_bytes/0.10.3/serde_bytes/

**Comment by vi** [comment]
Can it work if the array is buried inside like in `Option<(u32, Vec<([u8; 4], u16)>)>`?

**Comment by sfackler** [comment]
You can write a custom serializer. This isn't really specific to CBOR though.
