### ISSUE TITLE
Broken roundtrip serialization

### ISSUE THREAD

**Issue by RReverser** [pyfisch/cbor#57]
#54 (which attempted to fix #51 and #52) actually broke deserialization of Ipv4Addr (or, really, any other human-readability-dependant format) - `Deserializer` must have `is_human_readable` returning the same value as serializer.

Right now, if you try to serialize `Ipv4Addr`, it will serialize it as sequence of bytes, but will try to deserialize as a string, resulting in an error:

```
called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("invalid type:sequence, expected a string"), offset: 0 }
```

**Comment by pyfisch** [comment]
Do you or anyone else wants to send in a PR with a test for this?
