### ISSUE TITLE
How do deserialize a buffer of unknown size?

### ISSUE THREAD

**Issue by asomers** [pyfisch/cbor#61]
I would like to serialize a struct and store it in a file, padded out with zeroes to a fixed length.  But when I read the file in, including zeroes, and try to deserialize it, I get a `TrailingData` error.  It seems that `serde_cbor::from_vec` and `serde_cbor::from_reader` require the input to have precisely the expected size.  Do I have to store the packed structure's size and write that to the file too, outside of the packed structure?  That seems redundant.  It's also difficult, because `to_writer` does not return the amount of data written.

**Comment by sfackler** [comment]
You can manually construct a `Deserializer` and use that rather than the from_slice or from_reader convenience methods. Their implementations are really simple - just do the same thing and skip the call to `end()`: https://pyfisch.github.io/cbor/src/serde_cbor/de.rs.html#15-23

**Comment by asomers** [comment]
Thanks!  That's just what I was looking for.  For posterity, here's the working code:
```rust
let mut deserializer = serde_cbor::Deserializer::from_slice(myslice);
let myvalue: MyType = serde::Deserialize::deserialize(&mut deserializer).unwrap();
```
