### ISSUE TITLE
Detecting invalid cbor when deserializing multiple objects

### ISSUE THREAD

**Issue by maghis** [pyfisch/cbor#68]
I am deserializing multiple objects from a slice (like in https://github.com/pyfisch/cbor/issues/20).

I am using the EOF error to detect when I reached the last object, but I have no way to distinguish between an actual EOF and an invalid cbor object.

It would be great to have an `Iter` implementation that does the right thing or that the thrown error had not the current offset in the stream but the offset where the deserialization began.

**Comment by sfackler** [comment]
Can you check if the slice is empty rather than if you get an EOF error to detect the end of the sequence?

**Comment by maghis** [comment]
@sfackler is the slice being mutated by the deserializer?

**Comment by sfackler** [comment]
Could you show your code?

**Comment by maghis** [comment]
Sure, simplified:
```
fn decode_next<'a>(
    de: &mut serde_cbor::Deserializer<SliceRead<'a>>,
) -> Result<Option<Value>, CborError> {
    let res: Result<Value, CborError> = de::Deserialize::deserialize(de);
    match res {
        Ok(v) => Ok(Some(v)),
        Err(ref e) if e.is_eof() => Ok(None),
        Err(e) => Err(e),
    }
}

// I use it like:
let mut results = Vec::new();
loop {
    let res = decode_next(&mut deserializer)?;
    match res {
        Some(v) => {
            results.push(v);
        }
        None => {
            break;
        }
    };
}
```
It's not trivial to detect if cbor is invalid (it's very dense and almost every possible combination of values are valid) but having to rely on an error to know then the stream is finished vs failed seems like an hack.

Also, the above would be a lot better in an iter :)

**Comment by sfackler** [comment]
There are ways you can work around it but they're pretty convoluted. I opened up a PR to just add a `StreamDeserializer` which should be much easier to work with! #72.

**Comment by maghis** [comment]
Makes sense, thanks @sfackler!
