### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by jkcdarunday** [pyfisch/cbor#7]
I wonder if we can have support for Enums in a similar manner as serde_json does. Not sure if this will be breaking standards though. This would be a great addition.

**Comment by pyfisch** [comment]
What behavior do you expect? CBOR by itself does not have enums so there is no "natural" serialization.

**Comment by arthurprs** [comment]
Came here to ask the same. Since there's no natural option, maybe this crate could mimic serde_json behavior.

**Comment by iqualfragile** [comment]
this is actually a big blocker for me. interestingly it can serialize enums (or at least pretend to) but not deserialize them.
i wrote a testcase for you:
```
#![feature(custom_derive, plugin)]
#![plugin(serde_macros)]

extern crate serde_cbor;
use serde_cbor::{from_slice, to_vec};

#[derive(Debug,Serialize,Deserialize,PartialEq,Eq)]
enum Enum {
    A,  
    B,  
}

#[derive(Debug,Serialize,Deserialize,PartialEq,Eq)]
struct EnumStruct {
    e: Enum,
}

#[test]
fn test_enum() {
    let enum_struct = EnumStruct{ e: Enum::B };
    let re : EnumStruct = from_slice(&to_vec(&enum_struct).unwrap()).unwrap();
    assert_eq!(enum_struct, re);
}


#[repr(u16)]
#[derive(Debug,Serialize,Deserialize,PartialEq,Eq)]
enum ReprEnum {
    A,  
    B,  
}

#[derive(Debug,Serialize,Deserialize,PartialEq,Eq)]
struct ReprEnumStruct {
    e: ReprEnum,
}

#[test]
fn test_repr_enum() {
    let repr_enum_struct = ReprEnumStruct { e: ReprEnum::B };
    let re : ReprEnumStruct = from_slice(&to_vec(&repr_enum_struct).unwrap()).unwrap();
    assert_eq!(repr_enum_struct, re);
}


#[derive(Debug,Serialize,Deserialize,PartialEq,Eq)]
enum DataEnum {
    A(u32),
    B(u64),
}

#[test]
fn test_data_enum() {
    let data_enum = DataEnum::B(4);
    let re : DataEnum = from_slice(&to_vec(&data_enum).unwrap()).unwrap();
    assert_eq!(data_enum, re);
}
```

**Comment by iqualfragile** [comment]
also: expected behaviour: just serialize it to an u8/16/32/64

**Comment by pyfisch** [comment]
I am working on this. Serialization works, deserialization not yet.

How variants are serialized:
```
#[derive(Debug,Serialize,Deserialize,PartialEq,Eq)]
enum DataEnum {
    A, // A is serialized to 0
    B(u64), // B(42) is serialized to [1, 42]
    C(String, u8) // C("foo".to_owned(), 9) is serialized to [2, "foo", 9]
}
```

As you can see the variant indices are serialized and additional data is serialized as an array.

**Comment by pyfisch** [comment]
:tada: Enum serialization does now work.

@iqualfragile Variants are serialized to strings, because deserialization with strings is easier. Maybe I will add a "compact" mode in the future. Does this patch solve your problem? In this case I will merge it and update crates.io.

**Comment by iqualfragile** [comment]
@pyfisch it would have, yes, but i gave up a day ago, and switched to rustc_serialize for now, (sorry :( ) but i am sure being able to fully serialize rust data types will be extremly useful for others! So thanks for your work.

**Comment by pyfisch** [comment]
@iqualfragile The patch has been merged now. Are you working on some public project? Maybe there is later time to switch to serde. ;)

**Comment by iqualfragile** [comment]
it will soon-ish be public currently im just laying down the foundation
and yes, switching to serde is the plan, but maybe later (serde also has the downside of requiring nightly)
