### ISSUE TITLE
Support for indefinite length arrays

### ISSUE THREAD

**Issue by Don42** [pyfisch/cbor#74]
In the current draft, the bundle protocol [0] uses indefinite-length arrays in its binary representation.
While deserialization of those was easy, I have yet to find a way to serialize a data structure into
that format.

1. Is serialization of indefinite-length arrays supported?
2. Is it possible within the serde framework?
3. Is there a workaround?

[0] https://tools.ietf.org/html/draft-ietf-dtn-bpbis-11#section-4.2.1

**Comment by sfackler** [comment]
We do support serialization of indefinite-length arrays. An (optional) size is passed to [`Serializer::serialize_seq`](https://docs.rs/serde/1.0.79/serde/trait.Serializer.html#tymethod.serialize_seq), and if it's not set we use the indefinite length encoding. The `Serialize` implementations for `Vec<T>`, `&[T]`, etc will all provide the length but you should be able to make a small wrapper type that overrides that behavior.

**Comment by Don42** [comment]
Thanks for the hint. I'll take a look next chance I get.
I'll get back to you if I have another question.
