### ISSUE TITLE
Remove EOF check during deserialization?

### ISSUE THREAD

**Issue by gnuvince** [pyfisch/cbor#83]
I use bincode in one of my programs, and I'm interested in switching to CBOR to make interoperability with other languages easier.  One blocker that I have at the moment is the difficulty of quickly reading a small header struct in a very large file (2–4 GiB).  Consider these data structures:

    #[derive(Serialize, Deserialize)]
    struct Header {
        magic: u32,
        timestamp: i64
    }

    #[derive(Serialize, Deserialize)]
    struct Bucket {
        header: Header,
        data: HashMap<String, Info>
    }

If I serialize a `Bucket` to disk using bincode, I can then deserialize just the header:

    bincode::serialize_into(&mut writer, &my_bucket);
    let my_header: Header = bincode::deserialize_from(&mut reader).unwrap();

With serde_cbor, I need to read the entire file to get at the header, and that makes the program unacceptably slow.  I thought about serializing the header and the HashMap one after the other:

    serde_cbor::to_writer(&mut writer, &my_header);
    serde_cbor::to_writer(&mut writer, &my_data);

Unfortunately, this doesn't work: when I try to deserialize just the header, the deserializer asserts that the reader has been read entirely.[1]

Would it be possible to either remove this end-of-stream check or to add another deserializer function that doesn't return an error when there is still data in the buffer?

[1]: https://github.com/pyfisch/cbor/blob/master/src/de.rs#L75

**Comment by sfackler** [comment]
from_reader is a simple wrapper over `Deserializer`: https://github.com/pyfisch/cbor/blob/master/src/de.rs#L73-L76

You can just work with the Deserializer type yourself and not call eof() until desired.

**Comment by gnuvince** [comment]
Good idea @sfackler, I'll give that a try.  Thanks!
