### ISSUE TITLE
Change enum serialization

### ISSUE THREAD

**Issue by pyfisch** [pyfisch/cbor#85]
https://serde.rs/enum-representations.html

Serde CBOR should use the "Externally tagged" format by default in the next breaking version.
Also make sure that the other formats round-trip.
The current array based serialization should be kept as a legacy format so old data can be read.

**Comment by pyfisch** [comment]
@ogoodman @kostko I am considering to make the serialization from #67 the new default.

**Comment by kostko** [comment]
Yeah, I agree it would be more consistent. This would be a breaking change though as it would change the default serialization format.

**Comment by nifker** [comment]
@pyfisch I'm interested in enums(which are holding arguments) represent the enum type as integer - similiar to https://crates.io/crates/protocol - is this possible?
