### ISSUE TITLE
Support integer and other types as key

### ISSUE THREAD

**Issue by tiziano88** [pyfisch/cbor#87]
Currently there seems to be no way of specifying that a field of a struct correspond to a numeric key. I am not sure whether this would require an additional annotation, since even using `#[serde(rename = "1")]` would be ambiguous between the string "1" and the integer value 1.

**Comment by sfackler** [comment]
There is the packed format, where the index of the field is used instead of its name: https://docs.rs/serde_cbor/0.9.0/serde_cbor/struct.Serializer.html#method.packed

**Comment by tiziano88** [comment]
AFAICT that only works for serialization but not for deserialization? Also for my use case the indices are not contiguous, and in fact some of them are negative numbers, so the sequential numbering would not work anyways. WDYT?

**Comment by sfackler** [comment]
It does work for deserialization.

You may need to manually implement Serialize and Deserialize to get the behavior you're looking for.

**Comment by pyfisch** [comment]
@tiziano88 do sfackler's suggestions solve your problem?

**Comment by tiziano88** [comment]
I have not attempted writing my own Serialize and Deserialize methods yet, but I am intending to do so at some point. Will update this thread if / when that happens.

**Comment by pyfisch** [comment]
You can re-open the thread if / when the suggestions don't work.

**Comment by vi** [comment]
Can indexes be specified explicitly, like in Protobuf, instead of relying on struct field order?

Can it support mixed mode where basic, "required" items are numeric, but there can also be optional string-keyed fields?

**Comment by pyfisch** [comment]
> Can indexes be specified explicitly, like in Protobuf, instead of relying on struct field order?

Nope. You need to write your own serializers/deserializers.

> Can it support mixed mode where basic, "required" items are numeric, but there can also be optional string-keyed fields?

Only with custom (de)serializers. If you use implicit numeric indices you can mix them with strings.
