### ISSUE TITLE
Bad error deserializing empty map to ()

### ISSUE THREAD

**Issue by sfackler** [pyfisch/cbor#9]
A "long form" empty map will not deserialize:

```rust
extern crate serde_cbor;

fn main() {
    let _: () = serde_cbor::from_slice(&[191, 255]).unwrap();
}
```

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: TrailingBytes', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sfackler** [comment]
Ah, looks like it will deserialize to a `HashMap<String, String>` so it looks like it's specific to ()'s method of deserializing.

**Comment by pyfisch** [comment]
`let _: std::collections::HashMap<(), ()> = serde_cbor::from_slice(&[191, 255]).unwrap();` does also work. Maps are currently always deserialized to `HashMap`s.

**Comment by pyfisch** [comment]
@sfackler: Should I also deserialize the empty sequence to `()`? It would make sense I think.

**Comment by sfackler** [comment]
I think it's fine that you can't get a `()` from an empty map, but the error that's reported (`TrailingBytes`) seems wrong.

I think it would make sense that the empty sequence could deserialize to `()` since a 2-length sequence will deserialize to `(A, B)`.

**Comment by pyfisch** [comment]
I will look into error messages. This is a general problem with this crate but also with serde I think.

**Comment by pyfisch** [comment]
The `TrailingBytes` error was caused by a bug in error handling. Now the correct error is reported.
