### ISSUE TITLE
from_reader implementation using &mut Read

### ISSUE THREAD

**Issue by nifker** [pyfisch/cbor#93]
I have some types where I cant consume the reader and thus not use the from_reader function - would it be possible to change the implementation so use it uses a &mut Read?

**Comment by dtolnay** [comment]
Could you share a minimal example of the code you would like to be able to write that doesn't work currently?

**Comment by nifker** [comment]
Playground still has no CBOR support.
But the structs field is private and it is a network socket.

**Comment by dtolnay** [comment]
Would it be possible to put together a minimal example using std::fs::File or something else basic as the reader, to show what doesn't work? It's fine if it needs to be built outside of the playground.

**Comment by pyfisch** [comment]
probably related: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#generic-readerwriter-functions-take-r-read-and-w-write-by-value-c-rw-value

**Comment by nifker** [comment]
@pyfisch had the proper solution - kudos to you :D
