### ISSUE TITLE
Retrieve underlying error from error::Error

### ISSUE THREAD

**Issue by nifker** [pyfisch/cbor#94]
I would like to get the e.g. IO-Error from the Error type. So it would be senseful to implement source() or a custom method which can achieve this.

**Comment by sfackler** [comment]
Since we need to support Rust releases before `source` was stabilized, we should use https://crates.io/crates/rustc_version in a build script to conditionally compile the method.

**Comment by dtolnay** [comment]
Alternative: `From<serde_cbor::Error> for io::Error` which maps the other error categories appropriately.

**Comment by pyfisch** [comment]
Will be available in the next version.
